### ISSUE TITLE
wiki pages created from within a graph view appear in Term:UUID notation instead of clear name

### ISSUE THREAD

**Issue by MatPopp** [OpenSemanticLab/mediawiki-extensions-InteractiveSemanticGraph#13]
<img width="117" alt="Energiespeicher" src="https://user-images.githubusercontent.com/27500989/184127719-78b795e8-af9e-49d2-abc6-903b6d505f98.png">

<img width="159" alt="UUID" src="https://user-images.githubusercontent.com/27500989/184127732-f5bcc3af-97dc-41b3-9e75-b3254bd8d494.png">
 
After saving in the Term Template once (without changing anything) the appearence gets corrected

**Comment by simontaurus** [comment]
resolved by https://github.com/OpenSemanticLab/mediawiki-extensions-InteractiveSemanticGraph/commit/bb390a63c227ea2eee6cd7949bcf047ab5a2b83e
