### ISSUE TITLE
Inclusion of already existing but disconnected Terms

### ISSUE THREAD

**Issue by MatPopp** [OpenSemanticLab/mediawiki-extensions-InteractiveSemanticGraph#14]
This is related to #9 . 
Two already existing Terms that are so far not connected can at the moment only be pushed into the same graph via creating a relation in the form editor. 

Possibilities:
a) search wiki if page exists before creating a new page with same name => popup Window to confirm that the existing page is meant or not. ()
b) add Button "add existing node"  => might be easier to understand but will eventually mess up the GUI

**Comment by simontaurus** [comment]
Add node with autocomplete should assist user to identify existing term (and properties)

**Comment by MatPopp** [comment]
Issue solved by autocomplete feature
