### ISSUE TITLE
creation of nodes within the graph view

### ISSUE THREAD

**Issue by MatPopp** [OpenSemanticLab/mediawiki-extensions-InteractiveSemanticGraph#3]
* using the Edit => create Node buttons 
* optionally: using a shortcut (ctrl + N ?? => N for new or node)
* deletion of wiki pages within the graph is maybe not a good idea since it can destroy lots of work.

**Comment by MatPopp** [comment]
see issue #7

**Comment by simontaurus** [comment]
creating nodes and edges is already possible with the "edit" menu. Pages will be created with an UUID in the namespace "Term" and will use the Template KB/Term (see [OSL Extension](https://github.com/OpenSemanticLab/mediawiki-extensions-OpenSemanticLab/tree/main/importPages/OslTemplate/KB/Term)) to store properties and also allow form based editing.
Shortcuts => new Issue
Deleting pages: This is normally only possible for admins. It's also possible to undo any deletion

**Comment by MatPopp** [comment]
In my case it does not work. 
After clicking "save changes" => "OK" an error message "assertbotfailed" occurs in the  Browser console
![grafik](https://user-images.githubusercontent.com/27500989/184122329-66a9faab-72e3-401b-a9ed-375bf00849cc.png)

**Comment by MatPopp** [comment]
well... I had no bot rights. With bot rights I can create wiki pages from the graph 
however there is still an issue in the appearence #13

**Comment by simontaurus** [comment]
resolved by https://github.com/OpenSemanticLab/mediawiki-extensions-MwJson/commit/039b68e2bb0bbfa197e0e006ebf024d47e3c1d9f
