### ISSUE TITLE
multiple root nodes 

### ISSUE THREAD

**Issue by MatPopp** [OpenSemanticLab/mediawiki-extensions-InteractiveSemanticGraph#9]
* in order to showcase the connection between two (or more) terms

**Comment by simontaurus** [comment]
https://github.com/OpenSemanticLab/mediawiki-extensions-InteractiveSemanticGraph/commit/4d1ab52aa20c335ccebde25c370e7c4035011115 allows at least a manual added second "root" node by selecting an existing term

**Comment by MatPopp** [comment]
solved by search function for insert node
